"""Passages read in full on PHB PDF 212 and 240-242, lists visually reviewed."""
ROWS = [
 ('Acid Splash','Spruzzo Acido',212,0,'conjuration','action','60 feet',['V','S'],'Instantaneous',False,False,['sorcerer','wizard'],None,None,
  {'targetChoice':{'maximumCreatures':2,'twoTargetsMustBeWithinFt':5},'save':'dexterity','damage':'1d6','damageType':'acid','successfulSave':'no-damage',
   'damageDiceByCharacterLevel':{'1':'1d6','5':'2d6','11':'3d6','17':'4d6'}},
  {'kind':'character-level-scaling'},'Uno o due bersagli, distanti fra loro al massimo cinque piedi, subiscono danni acidi se falliscono il TS di Destrezza.'),
 ('Aid','Aiuto',212,2,'abjuration','action','30 feet',['V','S','M'],'8 hours',False,False,['cleric','paladin'],'Una piccola striscia di stoffa bianca',None,
  {'maximumTargets':3,'currentHitPointsIncrease':5,'maximumHitPointsIncrease':5},
  {'kind':'per-slot-above-base','base':2,'additionalCurrentAndMaximumHP':5},'Fino a tre creature aumentano di cinque sia i PF attuali sia quelli massimi per otto ore; non sono PF temporanei.'),
 ('Alarm','Allarme',212,1,'abjuration','minute','30 feet',['V','S','M'],'8 hours',True,False,['ranger','wizard'],'Un campanellino e un frammento di sottile filo argentato',None,
  {'targetChoice':['door','window','area-up-to-20-ft-cube'],'trigger':'non-exempt-tiny-or-larger-creature-touches-or-enters',
   'mayDesignateExemptCreatures':True,'alarmChoice':{'mental':{'casterMaximumDistanceMiles':1,'wakesSleepingCaster':True},'audible':{'radiusFt':60,'seconds':10}}},
  {'kind':'not-stated'},'Proteggi un accesso o una piccola area: un ingresso non autorizzato produce un avviso mentale o un suono udibile, a tua scelta.'),
 ('Fabricate','Fabbricare',240,4,'transmutation',(10,'minute'),'120 feet',['V','S'],'Instantaneous',False,False,['wizard'],None,None,
  {'rawMaterials':'visible-within-range-in-sufficient-quantity','materialPreserved':True,'quality':'commensurate-with-raw-materials',
   'maximumObject':{'normal':'Large','normalVolume':'10-ft-cube-or-eight-connected-5-ft-cubes','metalStoneMinerals':'Medium','mineralVolume':'single-5-ft-cube'},
   'cannotCreateOrTransmute':['creature','magic-item'],'skilledCraftRequires':'proficiency-in-corresponding-artisan-tools'},
  {'kind':'not-stated'},'Trasformi materiali grezzi in un oggetto dello stesso materiale. Dimensioni, qualità e competenza artigianale limitano il risultato.'),
 ('Faerie Fire','Luminescenza',240,1,'evocation','action','60 feet',['V'],'Concentration, up to 1 minute',False,True,['bard','druid'],None,None,
  {'area':{'shape':'cube','sideFt':20},'outlinedObjects':'all-in-area','creatureSave':'dexterity','failedSaveEffect':'outlined',
   'outlineColorChoices':['blue','green','violet'],'affectedTargetDimLightRadiusFt':10,'attackAdvantageRequires':'attacker-sees-affected-target','preventsInvisibilityBenefit':True},
  {'kind':'not-stated'},'Illumini gli oggetti e le creature che falliscono il TS: gli attacchi contro bersagli visibili hanno vantaggio e l’invisibilità non li protegge.'),
 ('False Life','Vita Falsata',240,1,'necromancy','action','Self',['V','S','M'],'1 hour',False,False,['sorcerer','wizard'],'Una piccola quantità di alcol o distillato',None,
  {'temporaryHitPoints':'1d4+4'},
  {'kind':'per-slot-above-base','base':1,'additionalTemporaryHitPoints':5},'Ottieni 1d4 più quattro PF temporanei per un’ora; ogni livello di slot aggiuntivo aumenta il beneficio di cinque.'),
 ('Fear','Paura',240,3,'illusion','action','Self (30-foot cone)',['V','S','M'],'Concentration, up to 1 minute',False,True,['bard','sorcerer','warlock','wizard'],'Una piuma bianca o il cuore di una gallina',None,
  {'area':{'shape':'cone','lengthFt':30},'save':'wisdom','failedSave':{'dropsHeldItems':True,'condition':'frightened'},
   'whileFrightened':{'mustDash':True,'route':'safest-available-away-from-caster','exception':'nowhere-to-move'},
   'repeatSave':{'when':'end-of-target-turn','requires':'no-line-of-sight-to-caster','ability':'wisdom','success':'ends-for-target'}},
  {'kind':'not-stated'},'Il cono terrorizza chi fallisce il TS: lascia ciò che impugna e fugge. Può ripetere il tiro se termina il turno senza vederti.'),
 ('Feather Fall','Caduta Morbida',240,1,'transmutation','reaction','60 feet',['V','M'],'1 minute',False,False,['bard','sorcerer','wizard'],'Una piccola piuma o del piumino',None,
  {'trigger':'caster-or-creature-within-60-ft-falls','maximumFallingCreatures':5,'fallingSpeedFtPerRound':60,
   'landingDuringSpell':{'fallDamage':0,'canLandOnFeet':True,'endsForCreature':True}},
  {'kind':'not-stated'},'Con una reazione rallenti la caduta di fino a cinque creature. Se atterrano mentre dura l’effetto, evitano i danni da caduta.'),
 ('Feeblemind','Regressione Mentale',[240,241],8,'enchantment','action','150 feet',['V','S','M'],'Instantaneous',False,False,['bard','druid','warlock','wizard'],'Una manciata di piccole sfere di argilla, cristallo, vetro o minerale',None,
  {'target':'visible-creature','damage':'4d6','damageType':'psychic','damageRequiresFailedSave':False,'save':'intelligence',
   'failedSave':{'intelligenceScore':1,'charismaScore':1,'cannot':['cast-spells','activate-magic-items','understand-language','intelligible-communication'],
                 'canStill':['recognize-friends','follow-friends','protect-friends']},
   'repeatSaveIntervalDays':30,'successfulRepeatSaveEnds':True,'removedBySpellIds':['phb2014:spell:greater-restoration','phb2014:spell:heal','phb2014:spell:wish']},
  {'kind':'not-stated'},'Infliggi danni psichici e, se il TS fallisce, riduci Intelletto e Carisma a uno impedendo magia e linguaggio. Nuovo TS ogni trenta giorni.'),
 ('Feign Death','Morte Apparente',241,3,'necromancy','action','Touch',['V','S','M'],'1 hour',True,False,['bard','cleric','druid','wizard'],'Un pizzico di terra di un cimitero',None,
  {'target':'willing-creature','appearsDeadTo':['outward-inspection','status-detection-spells'],'conditions':['blinded','incapacitated'],'speedFt':0,
   'damageResistance':'all-except-psychic','diseaseAndPoisonEffects':'suppressed-until-spell-ends','dismissal':'caster-action-and-touch'},
  {'kind':'not-stated'},'Un bersaglio consenziente sembra morto, non si muove ed è incapacitato; resiste ai danni salvo gli psichici e sospende gli effetti di malattia e veleno.'),
 ('Find Familiar','Trova Famiglio',241,1,'conjuration','hour','10 feet',['V','S','M'],'Instantaneous',True,False,['wizard'],'Carbone, incenso ed erbe per dieci mo, consumati dal fuoco in un braciere di ottone',10,
  {'materialConsumed':True,'forms':['bat','cat','crab','frog','hawk','lizard','octopus','owl','poisonous-snake','quipper','rat','raven','sea-horse','spider','weasel'],
   'appearanceSpace':'unoccupied-in-range','creatureTypeChoice':['celestial','fey','fiend'],'usesFormStatistics':True,'maximumFamiliars':1,
   'independentTurn':True,'ownInitiative':True,'obeysCommands':True,'cannotAttack':True,'otherActionsAllowed':True,
   'atZeroHP':'disappears-and-requires-recasting-to-return','telepathyRangeFt':100,
   'perceiveSenses':{'activation':'action','rangeFt':100,'expires':'start-of-caster-next-turn','includesSpecialSenses':True,'ownSensesConditions':['blinded','deafened']},
   'temporaryDismissal':{'activation':'action','destination':'pocket-dimension','returnActivation':'action','returnUnoccupiedSpaceWithinFt':30},
   'permanentDismissal':'action','recastWithExisting':'changes-to-another-listed-form',
   'deliverTouchSpell':{'familiarMaximumDistanceFt':100,'activation':'familiar-reaction-when-caster-casts','attackModifier':'caster-spell-attack-modifier'}},
  {'kind':'not-stated'},'Evoci uno spirito con forma animale, un proprio turno e nessun attacco. Puoi condividere i suoi sensi e fargli consegnare magie a contatto usando la sua reazione.'),
 ('Find Steed','Trova Cavalcatura',241,2,'conjuration',(10,'minute'),'30 feet',['V','S'],'Instantaneous',False,False,['paladin'],None,None,
  {'exampleForms':['warhorse','pony','camel','elk','mastiff'],'otherAnimalFormsRequireDM':True,'appearanceSpace':'unoccupied-in-range',
   'usesFormStatistics':True,'creatureTypeChoice':['celestial','fey','fiend'],'minimumIntelligence':6,'understandsChosenCasterLanguage':True,
   'mountInAndOutOfCombat':True,'whileMountedMayShare':'caster-spells-targeting-only-caster','atZeroHP':'disappears',
   'dismissal':'caster-action','recastAfterDisappearance':'same-steed-restored-to-maximum-hit-points',
   'telepathyRangeMiles':1,'maximumBondedSteeds':1,'releaseBond':'caster-action-and-steed-disappears'},
  {'kind':'not-stated'},'Uno spirito diventa una cavalcatura intelligente. Il legame permette telepatia entro un miglio e la condivisione di alcune magie mentre la monti.'),
 ('Find the Path','Trova il Cammino',[241,242],6,'divination','minute','Self',['V','S','M'],'Concentration, up to 1 day',False,True,['bard','cleric','druid'],'Strumenti divinatori da cento mo e un oggetto proveniente dal luogo da trovare',100,
  {'destination':'specific-fixed-familiar-location-on-same-plane','invalidDestinations':['another-plane','moving-location','unspecific-location'],
   'knowsDestinationDirectionAndDistance':'while-on-same-plane','atChoiceOfRoutes':'knows-shortest-most-direct-physical-route','safestRouteGuaranteed':False},
  {'kind':'not-stated'},'Conosci direzione, distanza e percorso fisico più breve verso un luogo preciso già familiare sullo stesso piano; il percorso non è necessariamente sicuro.'),
 ('Find Traps','Individuazione delle Trappole',242,2,'divination','action','120 feet',['V','S'],'Instantaneous',False,False,['cleric','druid','ranger'],None,None,
  {'detects':'intentionally-created-sudden-or-unexpected-harmful-or-undesirable-effects','requires':'line-of-sight',
   'reveals':['presence','general-danger-nature'],'doesNotReveal':'individual-trap-location','excludes':'natural-hazards-not-intentionally-created'},
  {'kind':'not-stated'},'Rilevi presenza e natura generale del pericolo delle trappole visibili entro gittata, senza sapere dove si trova ciascuna; i rischi naturali sono esclusi.'),
 ('Finger of Death','Dito della Morte',242,7,'necromancy','action','60 feet',['V','S'],'Instantaneous',False,False,['sorcerer','warlock','wizard'],None,None,
  {'target':'visible-creature','save':'constitution','damage':'7d8+30','damageType':'necrotic','successfulSave':'half',
   'humanoidKilled':{'becomes':'zombie','when':'start-of-caster-next-turn','control':'permanent-verbal-commands'}},
  {'kind':'not-stated'},'Il bersaglio subisce 7d8 più trenta danni necrotici, dimezzati dal TS; un umanoide ucciso si rialza come zombi sotto il tuo comando.'),
]
