import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { parseCatalog, searchCatalog, sheetFromCatalog, templateFromCatalog } from '../src/utils/Catalog.ts'
import { abilitiesFromSheet, parseCharacterSheets, newCharacterSheet } from '../src/utils/CharacterSheets.ts'

const raw = JSON.parse(readFileSync(new URL('../public/data/database.json', import.meta.url), 'utf8'))
const catalog = parseCatalog(raw)
assert.equal(catalog.creatures.length, 321)
assert.equal(catalog.abilities.length, 1534 + 319 + 574)
assert.equal(searchCatalog(catalog.creatures, '').length, 0)
assert.ok(searchCatalog(catalog.creatures, '  BOLE  ').some((entry) => entry.name === 'Aboleth'), 'Search must match inside a name, ignoring case and whitespace')
assert.ok(searchCatalog(catalog.abilities, 'abilita').some((entry) => entry.name.toLowerCase().includes('abilità')), 'Search must ignore accents')
assert.equal(searchCatalog(catalog.creatures, 'not-a-real-monster').length, 0)
assert.throws(() => parseCatalog(null))
assert.throws(() => parseCatalog({ ...raw, creatures: [{ id: 'bad', name: 'Bad', sourceUrl: 'javascript:alert(1)' }] }))
assert.throws(() => parseCatalog({ ...raw, spells: [{ ...raw.spells[0], durationInfo: { rounds: -1 } }] }))
const aboleth = catalog.creatures.find((entry) => entry.name === 'Aboleth')
const base = { ...newCharacterSheet(), name: 'Personalizzato' }
const sheet = sheetFromCatalog(aboleth, catalog, base)
assert.equal(sheet.id, base.id, 'Selecting a catalog entry while editing must preserve the saved sheet identity')
assert.equal(sheet.catalogId, aboleth.id)
assert.equal(sheet.kind, 'Mostro')
assert.equal(sheet.hitPoints, '135')
assert.equal(sheet.armorClass, '17')
assert.equal(sheet.strength, '21')
assert.equal(sheet.initiative, '', 'Selecting a monster must leave initiative empty for the roll')
assert.ok(sheet.notes.includes('Schiavizzare'))
assert.equal(sheet.abilities.length, aboleth.data.abilityIds.length)
assert.ok(sheet.abilities.every((ability) => ability.remainingTurns === 0 && ability.duration === 'Personalizzata'), 'Undefined monster ability durations must not be invented')
assert.deepEqual(parseCharacterSheets(JSON.stringify([sheet])), [sheet], 'Catalog links and custom durations must survive browser persistence')
assert.ok(abilitiesFromSheet(sheet, 42, 0).every((ability) => ability.ownerId === 42 && ability.catalogId && !ability.active))
const npc = catalog.creatures.find((entry) => entry.data.isNpc)
assert.equal(sheetFromCatalog(npc, catalog).kind, 'PNG')
const aid = catalog.abilities.find((entry) => entry.name === 'Aiuto')
const aidTemplate = templateFromCatalog(aid)
assert.equal(aidTemplate.duration, '8 ore')
assert.equal(abilitiesFromSheet({ ...sheet, abilities: [aidTemplate] }, 42, 0)[0].remainingTurns, 4800)
const custom = templateFromCatalog({ ...aid, rounds: 7 })
assert.equal(custom.duration, 'Personalizzata')
assert.equal(abilitiesFromSheet({ ...sheet, abilities: [custom] }, 42, 0)[0].remainingTurns, 7)
assert.equal(templateFromCatalog({ ...aid, rounds: 0 }).remainingTurns, 0)
assert.throws(() => parseCharacterSheets(JSON.stringify([{ ...sheet, abilities: [{ ...custom, remainingTurns: -1 }] }])))
assert.throws(() => parseCharacterSheets(JSON.stringify([{ ...sheet, catalogId: 5 }])))
const multiattacks = searchCatalog(catalog.abilities, 'Multiattacco')
assert.ok(new Set(multiattacks.map((entry) => entry.label)).size > 1, 'Same-name abilities must show the creature of origin')
assert.equal(new Set(catalog.abilities.map((entry) => entry.id)).size, catalog.abilities.length)
console.log('Catalog checks passed: substring search, autofill, ownership, persistence and durations')
