import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { parseCatalog, searchCatalog, sheetFromCatalog, templateFromCatalog, sheetWithCombatSpells, sheetWithCombatAbilities } from '../src/utils/Catalog.ts'
import { abilitiesFromSheet, parseCharacterSheets, newCharacterSheet, turnFromSheet, importSheetAbility } from '../src/utils/CharacterSheets.ts'

const raw = JSON.parse(readFileSync(new URL('../public/data/database.json', import.meta.url), 'utf8'))
const catalog = parseCatalog(raw)
assert.equal(catalog.creatures.length, 321)
assert.equal(catalog.abilities.length, raw.abilities.length + raw.spells.length + raw.spellIndex.length)
assert.equal(searchCatalog(catalog.creatures, '').length, 0)
assert.ok(searchCatalog(catalog.creatures, '  BOLE  ').some((entry) => entry.name === 'Aboleth'), 'Search must match inside a name, ignoring case and whitespace')
assert.ok(searchCatalog(catalog.abilities, 'abilita').some((entry) => entry.name.toLowerCase().includes('abilità')), 'Search must ignore accents')
assert.equal(searchCatalog(catalog.creatures, 'not-a-real-monster').length, 0)
assert.throws(() => parseCatalog(null))
assert.throws(() => parseCatalog({ ...raw, creatures: [{ id: 'bad', name: 'Bad', sourceUrl: 'javascript:alert(1)' }] }))
assert.throws(() => parseCatalog({ ...raw, spells: [{ ...raw.spells[0], durationInfo: { rounds: -1 } }] }))
const aboleth = catalog.creatures.find((entry) => entry.name === 'Aboleth')
const base = { ...newCharacterSheet(), name: 'Personalizzato' }
const { abilities: _abilities, ...legacySheet } = base
assert.deepEqual(turnFromSheet(legacySheet, 41).sheet.abilities, [], 'Legacy cards without ability arrays must still convert into combat turns')
assert.deepEqual(sheetWithCombatSpells(legacySheet, catalog).abilities, [], 'Combat ability expansion must tolerate legacy cards')
assert.deepEqual(sheetWithCombatAbilities(legacySheet, catalog).abilities, [], 'Combat ability conversion must tolerate legacy cards')
const sheet = sheetFromCatalog(aboleth, catalog, base)
assert.equal(sheet.id, base.id, 'Selecting a catalog entry while editing must preserve the saved sheet identity')
assert.equal(sheet.catalogId, aboleth.id)
assert.equal(sheet.kind, 'Mostro')
assert.equal(sheet.hitPoints, '135')
assert.equal(sheet.armorClass, '17')
assert.equal(sheet.strength, '21')
assert.equal(sheet.initiative, '', 'Selecting a monster must leave initiative empty for the roll')
assert.ok(sheet.notes.includes('Schiavizzare'))
assert.equal(sheet.abilities.length, aboleth.data.abilityIds.length)
assert.ok(sheet.abilities.every((ability) => ability.remainingTurns === 0 && ability.duration === 'Personalizzata'), 'Undefined monster ability durations must not be invented')
assert.deepEqual(parseCharacterSheets(JSON.stringify([sheet])), [sheet], 'Catalog links and custom durations must survive browser persistence')
assert.ok(abilitiesFromSheet(sheet, 42, 0).every((ability) => ability.ownerId === 42 && ability.catalogId && !ability.active))
const npc = catalog.creatures.find((entry) => entry.data.isNpc)
assert.equal(sheetFromCatalog(npc, catalog).kind, 'PNG')
for (const entry of [aboleth, npc]) {
    const snapshot = turnFromSheet(sheetFromCatalog(entry, catalog), 42)
    assert.equal(snapshot.sheet.abilities.length, entry.data.abilityIds.length, 'Monster and NPC cards retain all available templates')
    const imported = importSheetAbility([], snapshot.sheet, snapshot.id, 0, 100)
    assert.equal(imported.length, 1, 'A click imports only the requested monster or NPC ability')
    assert.equal(imported[0].catalogId, snapshot.sheet.abilities[0].catalogId)
    assert.equal(imported[0].ownerId, snapshot.id)
    assert.equal(imported[0].active, false)
    assert.equal(importSheetAbility(imported, snapshot.sheet, snapshot.id, 0, 101), imported, 'Repeated clicks keep the same card')
}
const aid = catalog.abilities.find((entry) => entry.name === 'Aiuto')
const aidTemplate = templateFromCatalog(aid)
assert.equal(aidTemplate.duration, '8 ore')
assert.equal(abilitiesFromSheet({ ...sheet, abilities: [aidTemplate] }, 42, 0)[0].remainingTurns, 4800)
const custom = templateFromCatalog({ ...aid, rounds: 7 })
assert.equal(custom.duration, 'Personalizzata')
assert.equal(abilitiesFromSheet({ ...sheet, abilities: [custom] }, 42, 0)[0].remainingTurns, 7)
assert.equal(templateFromCatalog({ ...aid, rounds: 0 }).remainingTurns, 0)
assert.throws(() => parseCharacterSheets(JSON.stringify([{ ...sheet, abilities: [{ ...custom, remainingTurns: -1 }] }])))
assert.throws(() => parseCharacterSheets(JSON.stringify([{ ...sheet, catalogId: 5 }])))
const multiattacks = searchCatalog(catalog.abilities, 'Multiattacco')
assert.ok(new Set(multiattacks.map((entry) => entry.label)).size > 1, 'Same-name abilities must show the creature of origin')
assert.equal(new Set(catalog.abilities.map((entry) => entry.id)).size, catalog.abilities.length)
const caster = { ...base, abilities: [aidTemplate], playerDetails: {
    'spell.2.0.name': 'Aid', 'spell.0.0.name': 'Light', 'spell.1.1.name': 'Magia personale',
    'spell.1.2.name': 'Magia personale', 'spell.2.0.prepared': 'true', 'spell.1.3.name': ' ',
} }
const spellSheet = sheetWithCombatSpells(caster, catalog)
assert.equal(spellSheet.abilities.length, 3, 'Selected spells should be listed once alongside existing ability templates')
assert.ok(spellSheet.abilities.some((ability) => ability.name === 'Luce' && ability.catalogId))
assert.ok(spellSheet.abilities.some((ability) => ability.name === 'Magia personale' && ability.remainingTurns === 0))
assert.equal(caster.abilities.length, 1, 'Preparing the combat list must not modify the saved sheet')
assert.equal(sheetWithCombatSpells(sheet, catalog), sheet, 'Monster imports retain their current behavior')
console.log('Catalog checks passed: substring search, autofill, ownership, persistence and durations')

assert.ok(!catalog.abilities.some((entry) => entry.name === 'Aid'), 'Italian translations take precedence over duplicate English spells')
assert.ok(catalog.abilities.some((entry) => entry.name === 'Booming Blade' && entry.data.language === 'en'), 'Missing Italian translations stay available in English')
assert.equal(raw.englishSpells.length, raw.spellComparison.englishCount)
assert.equal(raw.spellIndex.length, raw.spellComparison.missingItalianCount)

const englishCatalog = parseCatalog(raw, 'en')
const englishAid = englishCatalog.abilities.find((entry) => entry.name === 'Aid')
assert.ok(englishAid)
assert.equal(englishAid.id, aid.id, 'Changing language preserves spell identity and saved references')
assert.ok(!englishCatalog.abilities.some((entry) => entry.name === 'Aiuto'))
assert.ok(searchCatalog(englishCatalog.abilities, 'aiuto').some((entry) => entry.id === englishAid.id), 'Search recognizes saved Italian names even in English mode')
assert.ok(searchCatalog(catalog.abilities, 'acid arrow').some((entry) => entry.name === 'Freccia Acida'), 'Search recognizes SRD aliases')
assert.equal(englishCatalog.abilities.filter((entry) => typeof entry.data.level === 'number').length, 574)
assert.equal(catalog.abilities.filter((entry) => typeof entry.data.level === 'number').length, 574)
assert.equal(catalog.abilities.filter((entry) => entry.data.language === 'en').length, 255)
const englishFromItalianSheet = sheetWithCombatSpells({ ...base, abilities: [], playerDetails: { 'spell.2.0.name': 'Aiuto', 'spell.2.1.name': 'Aid' } }, englishCatalog)
assert.equal(englishFromItalianSheet.abilities.length, 1, 'Switching language must not duplicate saved spells')
assert.equal(englishFromItalianSheet.abilities[0].name, 'Aid')
assert.equal(englishFromItalianSheet.abilities[0].catalogId, aid.id)
const italianFromEnglishSheet = sheetWithCombatSpells({ ...base, abilities: [], playerDetails: { 'spell.2.0.name': "Melf's Acid Arrow" } }, catalog)
assert.equal(italianFromEnglishSheet.abilities[0].name, 'Freccia Acida')
assert.equal(templateFromCatalog(englishAid).remainingTurns, aidTemplate.remainingTurns)
assert.equal(englishCatalog.creatures[0].id, catalog.creatures[0].id)
console.log('Spell language checks passed: Italian fallback, full English catalog, aliases and stable saved references')
