import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {newCharacterSheet,parseCharacterSheets,turnFromSheet} from '../src/utils/CharacterSheets.ts'
import {applyCreation,enableCreation,updateCharacterField,characterFieldValue,characterCalculationIssues} from '../src/utils/PlayerCreation.ts'
import {addInventoryItem,inventoryItems,inventoryCarriedWeight,inventoryReferenceKey,inventoryIssues,referencedInventoryItem,removeInventoryItem,setInventoryReference,setWornInventoryReferences,resolveInventoryPending} from '../src/utils/Inventory.ts'
import {parseTutorialDraft,changeTutorialOrigin} from '../src/utils/CharacterTutorial.ts'
const json=(file)=>JSON.parse(readFileSync(new URL(`../public/data/${file}.json`,import.meta.url),'utf8'))
const data={...json('character-options'),...json('character-equipment'),skills:json('character-rules').skills}
const create=()=>enableCreation({...newCharacterSheet(),name:'Inventario test',level:'1',strength:'14',dexterity:'14',constitution:'14',intelligence:'16',wisdom:'10',charisma:'10',playerDetails:{'creation.class':'wizard','creation.background':'acolyte','choice.class.wizard.equipment.0.0':'1','choice.class.wizard.equipment.1.0':'0','choice.class.wizard.equipment.2.0':'1','choice.background.acolyte.equipment.0.0':'0'}},data)
const edit=(sheet,key,value)=>applyCreation(updateCharacterField(sheet,key,value),data)
let sheet=create()
const items=inventoryItems(sheet)
assert.ok(items.some(x=>x.catalog==='spellbook'))
assert.ok(items.some(x=>x.catalog==='dagger'))
assert.ok(items.some(x=>x.catalog==='clothes-common'))
assert.ok(items.some(x=>x.catalog==='component-pouch'))
assert.ok(items.some(x=>x.catalog==='backpack'))
assert.ok(items.some(x=>x.catalog==='torch'&&x.quantity==='10'))
assert.ok(items.some(x=>x.catalog==='rations-1-day'&&x.quantity==='10'))
assert.ok(!items.some(x=>x.catalog==='explorers-pack'),'Do not also count the packed kit as a second object')
assert.equal(new Set(items.map(x=>x.id)).size,items.length)
assert.deepEqual(applyCreation(sheet,data),sheet,'Repeated calculation never grants the kit twice')
assert.equal(inventoryItems(applyCreation(sheet,data)).length,items.length)
let dagger=items.find(x=>x.catalog==='dagger')
assert.equal(dagger.weight,'0.45359237','Convert catalog pounds to kg exactly once')
assert.equal(referencedInventoryItem(sheet,'attacks.0.0').id,dagger.id)
sheet=setInventoryReference(sheet,'worn.weapon.0',dagger.id)
sheet=setInventoryReference(sheet,'magicItem.0.name',dagger.id)
sheet=setInventoryReference(sheet,'magicItem.1.name',dagger.id)
sheet=edit(sheet,'magicItem.0.notes','Lama della famiglia')
sheet=edit(sheet,'magicItem.1.attuned','true')
assert.equal(characterFieldValue(sheet,'magicItem.1.notes'),'Lama della famiglia')
assert.equal(characterFieldValue(sheet,'magicItem.0.attuned'),'true')
sheet=edit(sheet,`inventory.${dagger.row}.0`,'Pugnale di Aria')
for(const key of ['attacks.0.0','worn.weapon.0','magicItem.0.name','magicItem.1.name']) assert.equal(characterFieldValue(sheet,key),'Pugnale di Aria')
sheet=edit(sheet,`inventory.${dagger.row}.2`,'3')
sheet=edit(sheet,`inventory.${dagger.row}.1`,'0,25')
assert.equal(characterFieldValue(sheet,`inventory.${dagger.row}.3`),'0.75')
assert.equal(inventoryItems(sheet).find(x=>x.id===dagger.id).quantity,'3')
sheet=edit(sheet,`inventory.${dagger.row}.damageDice`,'2d4')
assert.match(sheet.playerDetails['attacks.0.2'],/^2d4/)
const weightBeforeRefs=inventoryCarriedWeight(sheet)
sheet=setInventoryReference(sheet,'worn.weapon.1',dagger.id)
assert.equal(inventoryCarriedWeight(sheet),weightBeforeRefs,'Several references never add another copy or weight')
// The same stable ID survives moving physical rows, changing template, reopening and combat.
const d={...sheet.playerDetails}
for (const key of Object.keys(d).filter(k=>k.startsWith(`inventory.${dagger.row}.`))) {d[key.replace(`inventory.${dagger.row}.`,'inventory.80.')]=d[key];delete d[key]}
sheet={...sheet,playerDetails:d}
assert.equal(referencedInventoryItem(sheet,'magicItem.0.name').row,80)
for(const template of ['generic','wizard','wizard-pdf']) {
 const reopened=applyCreation(parseCharacterSheets(JSON.stringify([{...sheet,playerDetails:{...sheet.playerDetails,'sheet.template':template}}]))[0],data)
 assert.equal(referencedInventoryItem(reopened,'attacks.0.0').id,dagger.id)
 assert.equal(characterFieldValue(reopened,'worn.weapon.0'),'Pugnale di Aria')
 assert.equal(turnFromSheet(reopened,2).sheet.playerDetails[inventoryReferenceKey('magicItem.1.name')],dagger.id)
}
assert.equal(parseTutorialDraft(JSON.stringify({...sheet,playerDetails:{...sheet.playerDetails,'tutorial.active':'true'}})).playerDetails[inventoryReferenceKey('attacks.0.0')],dagger.id)
let changed=changeTutorialOrigin(sheet,data,'class','fighter')
assert.ok(inventoryItems(changed).some(x=>x.id===dagger.id),'An edited starting object survives changing class')
changed=addInventoryItem(changed,data,'Tesoro','', '2')
const treasure=inventoryItems(changed).find(x=>x.name==='Tesoro')
changed=changeTutorialOrigin(changed,data,'class','wizard')
assert.ok(inventoryItems(changed).some(x=>x.id===treasure.id))
assert.ok(inventoryItems(changed).some(x=>x.id===dagger.id))
const removed=applyCreation(removeInventoryItem(sheet,dagger.id),data)
assert.equal(characterFieldValue(removed,'worn.weapon.0'),'')
assert.equal(characterFieldValue(removed,'magicItem.0.notes'),'')
assert.ok(inventoryIssues(removed).some(x=>x.includes('rimosso')))
assert.ok(!inventoryItems(removed).some(x=>x.id===dagger.id),'Deleting a generated object never grants it again')
assert.deepEqual(applyCreation(removed,data),removed)
let free=applyCreation({...newCharacterSheet(),name:'Manuale',playerDetails:{}},data)
free=applyCreation(addInventoryItem(free,data,'Omonimo'),data)
free=applyCreation(addInventoryItem(free,data,'Omonimo'),data)
assert.equal(inventoryItems(free).length,2)
assert.notEqual(inventoryItems(free)[0].id,inventoryItems(free)[1].id)
free=setInventoryReference(free,'worn.weapon.0',inventoryItems(free)[0].id)
free=applyCreation(removeInventoryItem(free,inventoryItems(free)[0].id),data)
assert.equal(characterFieldValue(free,'worn.weapon.0'),'','A namesake must not silently replace a removed object')
let legacy=applyCreation({...newCharacterSheet(),name:'Vecchia scheda',playerDetails:{equipment:'2 × Potion\n1 × Rope', 'inventory.0.0':'Potion','inventory.0.1':'0.5','inventory.0.2':'2','magicItem.0.name':'Potion','magicItem.0.notes':'Cura 2d4','magicItem.0.attuned':'true','worn.weapon.0':'Martello antico'}},data)
assert.equal(inventoryItems(legacy).filter(x=>x.name==='Potion').length,1,'Ambiguous name-only migration never creates another copy')
assert.ok(inventoryItems(legacy).some(x=>x.name==='Rope'))
assert.ok(inventoryItems(legacy).some(x=>x.name==='Martello antico'))
assert.ok(legacy.playerDetails['inventory.pending.magicItem.0.name'])
assert.ok(legacy.playerDetails['inventory.pending.equipment.0'])
assert.equal(JSON.parse(legacy.playerDetails['inventory.legacy'])['magicItem.0.notes'],'Cura 2d4')
assert.deepEqual(applyCreation(legacy,data),legacy,'A migration is idempotent')
const potion=inventoryItems(legacy).find(x=>x.name==='Potion')
legacy=applyCreation(resolveInventoryPending(legacy,'inventory.pending.magicItem.0.name',potion.id,data),data)
assert.equal(characterFieldValue(legacy,'magicItem.0.notes'),'Cura 2d4')
assert.equal(characterFieldValue(legacy,'magicItem.0.attuned'),'true')
legacy=applyCreation(resolveInventoryPending(legacy,'inventory.pending.equipment.0',potion.id,data),data)
assert.equal(inventoryItems(legacy).filter(x=>x.name==='Potion').length,1)
assert.ok(!legacy.playerDetails['inventory.pending.equipment.0'])
const ambiguous=enableCreation({...newCharacterSheet(),name:'Dotazione precedente',level:'1',intelligence:'16',playerDetails:{'creation.class':'wizard','creation.auto.equipment':'1 × Spellbook',equipment:'1 × Spellbook','inventory.0.0':'Spellbook','inventory.0.2':'1','inventory.0.1':'1'}},data)
assert.equal(inventoryItems(ambiguous).filter(x=>x.name==='Spellbook').length,1)
assert.ok(Object.keys(ambiguous.playerDetails).some(k=>k.startsWith('inventory.pending.grant.')))
assert.deepEqual(applyCreation(ambiguous,data),ambiguous,'Ambiguous grants stay pending instead of duplicating on the next update')
let packed=addInventoryItem({...newCharacterSheet(),name:'Pacco'},data,"Explorer's Pack",'explorers-pack','2')
assert.equal(inventoryItems(packed).find(x=>x.catalog==='torch').quantity,'20')
assert.equal(inventoryItems(packed).filter(x=>x.catalog==='backpack').length,1)
let armor=enableCreation({...newCharacterSheet(),name:'Armatura',level:'1',dexterity:'14',strength:'14',constitution:'14',playerDetails:{'creation.class':'wizard'}},data)
armor=applyCreation(addInventoryItem(armor,data,'Armatura acquistata','leather-armor'),data)
const armorItem=inventoryItems(armor).find(x=>x.catalog==='leather-armor')
armor=applyCreation(setInventoryReference(armor,'armor',armorItem.id),data)
assert.equal(armor.armorClass,'13','Purchased armor uses the same formulas as the starting kit')
armor=edit(armor,`inventory.${armorItem.row}.armorBase`,'14')
assert.equal(armor.armorClass,'16')
armor=edit(armor,`inventory.${armorItem.row}.armorBase`,'abc')
assert.ok(characterCalculationIssues(armor).length)
assert.ok(!Object.values(armor.playerDetails).includes('NaN'))
const corrupt=applyCreation({...sheet,playerDetails:{...sheet.playerDetails,'inventory.grants':'{invalid'}},data)
assert.equal(corrupt.playerDetails['inventory.grants'],'{invalid')
assert.ok(inventoryIssues(corrupt).some(x=>x.includes('non è leggibile')))
console.log('Inventory checks passed: kit contents, quantities, stable IDs, shared views, properties/calculations, references without duplicated weight, deletion, class/template changes, migration, ambiguous names, persistence and combat.')

let multiple=create()
const worn=inventoryItems(multiple).filter(x=>['dagger','backpack'].includes(x.catalog))
multiple=applyCreation(setWornInventoryReferences(multiple,'worn.Vita',worn.map(x=>x.id)),data)
assert.equal(characterFieldValue(multiple,'worn.Vita').split('\n').length,2)
assert.equal(characterFieldValue(applyCreation(removeInventoryItem(multiple,worn[0].id),data),'worn.Vita'),worn[1].name)
assert.ok(inventoryIssues(applyCreation(removeInventoryItem(multiple,worn[0].id),data)).some(x=>x.includes('rimosso')))
let weight=applyCreation(addInventoryItem({...newCharacterSheet(),name:'Pesi'},data,'A','','2'),data)
const a=inventoryItems(weight)[0]
weight=edit(weight,`inventory.${a.row}.1`,'0,5')
assert.equal(weight.playerDetails.carriedWeight,'1')
weight=edit(weight,`inventory.${a.row}.2`,'0')
assert.equal(weight.playerDetails.carriedWeight,'0')
weight=edit(weight,`inventory.${a.row}.2`,'1.5')
assert.equal(weight.playerDetails.carriedWeight,'')
assert.ok(characterCalculationIssues(weight).length)
const sameName=addInventoryItem({...newCharacterSheet(),name:'Nome'},data,'Pugnale personalizzato','dagger')
assert.equal(inventoryItems(sameName)[0].name,'Pugnale personalizzato','Keep custom names when adding a catalog item')
console.log('Inventory edge checks passed: multiple worn references, partial removal, decimal weights, zero/invalid quantities and custom catalog names.')

const recoveredPack=applyCreation({...newCharacterSheet(),name:'Vecchio pacchetto',playerDetails:{equipment:"2 × Explorer's Pack"}},data)
assert.equal(inventoryItems(recoveredPack).find(x=>x.catalog==='torch').quantity,'20')
assert.ok(!inventoryItems(recoveredPack).some(x=>x.catalog==='explorers-pack'))
assert.deepEqual(applyCreation(recoveredPack,data),recoveredPack)

const kit=create(),manual=applyCreation({...kit,playerDetails:{...kit.playerDetails,'creation.enabled':'false'}},data)
assert.deepEqual(inventoryItems(manual),inventoryItems(kit),'Switching to manual calculations must preserve starting equipment')
let marked=create()
const markedItem=inventoryItems(marked).find(x=>x.catalog==='dagger')
marked=edit(marked,`inventory.${markedItem.row}.consumable`,'true')
marked=edit(marked,'creation.class','fighter')
assert.ok(inventoryItems(marked).some(x=>x.id===markedItem.id),'Edited item flags must survive changing creation choices')
const empty={...newCharacterSheet(),name:'Vuoto',playerDetails:{'inventory.version':'1'}}
assert.deepEqual(updateCharacterField(empty,'magicItem.0.notes','Descrizione senza oggetto'),empty,'Unlinked descriptions cannot become phantom inventory items')
