import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { newCharacterSheet, parseCharacterSheets } from '../src/utils/CharacterSheets.ts'
import { enableCreation, spellSelection, selectedOrigins } from '../src/utils/PlayerCreation.ts'
import { spellRowState } from '../src/utils/Spellcasting.ts'
import { castWizardSpell, copyCost, copyWizardSpell, recoverWizardSlots, wizardBookIssues, wizardRest, wizardRules } from '../src/utils/Wizard.ts'
import { pdfAbilities } from '../src/utils/PlayerAbilities.ts'
import { parseCatalog, sheetWithCombatAbilities } from '../src/utils/Catalog.ts'
const json = (name) => JSON.parse(readFileSync(new URL(`../public/data/${name}.json`, import.meta.url), 'utf8'))
const data = { ...json('character-options'), ...json('character-equipment'), skills: json('character-rules').skills }
const catalog = parseCatalog(json('database'))
const create = (level, edition = '2014') => enableCreation({ ...newCharacterSheet(), name: 'Mago', kind: 'PG', level: String(level), intelligence: '16', constitution: '14', playerDetails: { 'creation.class': 'wizard', 'creation.subclass': 'evocation', 'rules.edition': edition } }, data)
const spell = (id) => data.spells.find((x) => x.index === id)
function add(sheet, id, index = 0, prepared = true) {
    const s = spell(id), root = `spell.${s.level}.${index}`
    return { ...sheet, playerDetails: { ...sheet.playerDetails, [`${root}.name`]: s.name, [`${root}.index`]: id, [`${root}.prepared`]: String(prepared) } }
}
const casting = (root, slot, extra = {}) => ({ root, slot, mode: 'slot', overchannel: false, selfDamage: '', empowered: false, damage: '', dice: '', targets: [], outcome: 'hit', ...extra })
assert.equal(wizardRules(create(2)).sculpt, true)
assert.equal(wizardRules(create(2, '2024')).sculpt, false)
assert.equal(wizardRules(create(3, '2024')).potent, true)
assert.equal(wizardRules(create(5)).potent, false)
assert.equal(wizardRules(create(6, '2024')).sculpt, true)
assert.equal(selectedOrigins(create(2, '2024'), data).subclass, undefined)
assert.ok(!create(2, '2024').playerDetails.classFeatures.includes('Evocation Savant'))
assert.ok(create(3, '2024').playerDetails.classFeatures.includes('Potent Cantrip (livello 3)'))
assert.ok(create(6, '2024').playerDetails.classFeatures.includes('Sculpt Spells (livello 6)'))
assert.equal(copyCost(create(3), spell('burning-hands')).gold, 25)
assert.equal(copyCost(create(3), spell('shield')).hours, 2)
assert.equal(copyCost(create(3, '2024'), spell('burning-hands')).gold, 50)
let mage = create(14)
mage.playerDetails['coins.MO'] = '100'
const copied = copyWizardSpell(mage, data, 'burning-hands')
assert.equal(copied.playerDetails['coins.MO'], '75')
assert.equal(copied.playerDetails['spell.1.0.learned'], 'copied')
assert.equal(copied.playerDetails['spell.1.0.prepared'], 'false')
assert.equal(mage.playerDetails['coins.MO'], '100', 'Operations must not mutate saved drafts')
assert.throws(() => copyWizardSpell(copied, data, 'burning-hands'), /già nel libro/)
assert.throws(() => copyWizardSpell({ ...mage, playerDetails: { ...mage.playerDetails, 'coins.MO': 'NaN' } }, data, 'shield'))
assert.throws(() => copyWizardSpell(create(1), data, 'fireball'))
assert.throws(() => copyWizardSpell(create(1), data, 'shield'), /Servono/)
let recovery = create(4)
Object.assign(recovery.playerDetails, { 'slots.1.used': '2', 'slots.2.used': '1' })
assert.throws(() => recoverWizardSlots(recovery, { 1: '1', 2: '1' }), /totale/)
assert.throws(() => recoverWizardSlots(recovery, { 1: '3' }), /effettivamente/)
assert.throws(() => recoverWizardSlots(recovery, { 6: '1' }))
assert.throws(() => recoverWizardSlots(recovery, { 1: '-1' }))
const recovered = recoverWizardSlots(recovery, { 2: '1' })
assert.equal(recovered.playerDetails['slots.2.used'], '0')
assert.throws(() => recoverWizardSlots(recovered, { 1: '1' }), /non disponibile/)
assert.equal(wizardRest(recovered, false).playerDetails['wizard.recovery.used'], 'true')
assert.equal(wizardRest(recovered, true).playerDetails['wizard.recovery.used'], 'false')
assert.equal(wizardRest(recovered, true).playerDetails['slots.1.used'], '0')
mage = add(mage, 'fireball')
const root = 'spell.3.0'
const first = castWizardSpell(mage, data, casting(root, 3, { overchannel: true, dice: '8d6', empowered: true, targets: ['Alleato'] }))
assert.equal(first.playerDetails['slots.3.used'], '1')
assert.equal(first.playerDetails['wizard.overchannel.used'], '1')
assert.ok(first.playerDetails['wizard.lastCast'].includes('Danno del tiro: 51'))
assert.ok(first.playerDetails['wizard.lastCast'].includes('Alleato'))
assert.throws(() => castWizardSpell(first, data, casting(root, 3, { overchannel: true, dice: '8d6' })), /Tira 6d12/)
const second = castWizardSpell({ ...first, playerDetails: { ...first.playerDetails, temporaryHitPoints: '5' } }, data, casting(root, 3, { overchannel: true, dice: '8d6', selfDamage: '20' }))
assert.equal(second.hitPoints, String(Number(first.hitPoints) - 15))
assert.equal(second.playerDetails.temporaryHitPoints, '0')
assert.equal(second.playerDetails['wizard.overchannel.used'], '2')
assert.throws(() => castWizardSpell(second, data, casting(root, 3, { overchannel: true, dice: '8d6', selfDamage: '8' })), /Tira 9d12/)
assert.equal(wizardRest(second, true).playerDetails['wizard.overchannel.used'], '0')
assert.throws(() => castWizardSpell(mage, data, casting(root, 6, { overchannel: true, dice: '8d6' })))
assert.throws(() => castWizardSpell(mage, data, casting(root, 3, { targets: ['A', 'a'] })))
assert.throws(() => castWizardSpell(mage, data, casting(root, 3, { targets: ['A','B','C','D','E'] })))
assert.throws(() => castWizardSpell(mage, data, casting(root, 3, { overchannel: true, dice: '0d6' })))
assert.throws(() => castWizardSpell({ ...mage, playerDetails: { ...mage.playerDetails, 'slots.3.used': mage.playerDetails['slots.3.total'] } }, data, casting(root, 3)), /slot disponibili/)
const lowInt = castWizardSpell({ ...mage, intelligence: '8' }, data, casting(root, 3, { damage: '10', empowered: true }))
assert.ok(lowInt.playerDetails['wizard.lastCast'].includes('Danno del tiro: 9'), 'Do not apply Wikidot’s erroneous minimum +1 Intelligence bonus')
let ritual = add(create(1), 'detect-magic', 0, false)
assert.equal(spellRowState(ritual, 1, 0).available, false)
assert.throws(() => castWizardSpell(ritual, data, casting('spell.1.0', 1)))
ritual = castWizardSpell(ritual, data, casting('spell.1.0', 1, { mode: 'ritual' }))
assert.equal(ritual.playerDetails['slots.1.used'], undefined)
assert.ok(ritual.playerDetails['wizard.lastCast'].includes('10 minuti'))
assert.throws(() => castWizardSpell(add(create(3), 'magic-missile'), data, casting('spell.1.0', 1, { mode: 'ritual' })))
for (const edition of ['2014', '2024']) {
    const cantrip = add(create(6, edition), 'acid-splash')
    const result = castWizardSpell(cantrip, data, casting('spell.0.0', 0, { damage: '9', outcome: 'save' }))
    assert.ok(result.playerDetails['wizard.lastCast'].includes('Danno del tiro: 4'))
    const attack = add(create(6, edition), 'ray-of-frost')
    const missed = castWizardSpell(attack, data, casting('spell.0.0', 0, { damage: '9', outcome: 'miss' }))
    assert.equal(missed.playerDetails['wizard.lastCast'].includes('Potent Cantrip'), edition === '2024')
}
for (const edition of ['2014', '2024']) {
    let high = add(add(add(create(20, edition), 'magic-missile', 0, false), 'misty-step', 0, false), 'fireball', 0, false)
    Object.assign(high.playerDetails, { 'wizard.mastery.1': 'spell.1.0', 'wizard.mastery.2': 'spell.2.0', 'wizard.signature.0': root })
    assert.equal(spellRowState(high, 1, 0).available, edition === '2024')
    assert.equal(spellRowState(high, 3, 0).countsPrepared, false)
    assert.equal(spellRowState(high, 3, 0).canToggle, false)
    assert.equal(spellRowState(high, 3, 0).available, true)
    assert.equal(spellSelection(high, data).prepared, 0)
    assert.ok(sheetWithCombatAbilities(high, catalog).abilities.some((x) => x.name === 'Palla di Fuoco'))
    if (edition === '2014') assert.throws(() => castWizardSpell(high, data, casting('spell.1.0', 1, { mode: 'mastery' })), /Prepara/)
    high.playerDetails['spell.1.0.prepared'] = 'true'
    const mastered = castWizardSpell(high, data, casting('spell.1.0', 1, { mode: 'mastery' }))
    assert.equal(mastered.playerDetails['slots.1.used'], undefined)
    if (edition === '2024') assert.throws(() => castWizardSpell(high, data, casting('spell.2.0', 2, { mode: 'mastery' })), /Spell Mastery/)
    const signature = castWizardSpell(high, data, casting(root, 3, { mode: 'signature' }))
    assert.throws(() => castWizardSpell(signature, data, casting(root, 3, { mode: 'signature' })), /non disponibile/)
    const reset = wizardRest(signature, false)
    assert.doesNotThrow(() => castWizardSpell(reset, data, casting(root, 3, { mode: 'signature' })))
    assert.doesNotThrow(() => castWizardSpell(signature, data, casting(root, 4)), 'Signature spells may still be cast using slots')
}
const nonEvocation = create(14)
nonEvocation.playerDetails['creation.subclass'] = ''
assert.equal(wizardRules(nonEvocation).overchannel, false)
const features = pdfAbilities(create(14))
assert.equal(features.find((x) => x.name === 'Overchannel').activation, 'active')
assert.equal(features.find((x) => x.name === 'Evocation Savant').activation, 'passive')
assert.equal(features.find((x) => x.name === 'Empowered Evocation').activation, 'passive')
let savant = add(create(3, '2024'), 'fireball')
savant.playerDetails['spell.3.0.learned'] = 'savant'
assert.ok(wizardBookIssues(savant, data).some((x) => x.includes('due magie iniziali')))
savant = add(create(3, '2024'), 'burning-hands')
savant.playerDetails['spell.1.0.learned'] = 'savant'
assert.deepEqual(wizardBookIssues(savant, data), [])
assert.deepEqual(parseCharacterSheets(JSON.stringify([second]))[0], second)
console.log('Wizard checks passed: edition gates, spellbook copies, recovery, rituals, mastery, signature, evocation, Overchannel, persistence and combat imports.')
const freeHigh = add(add(add(create(3), 'acid-arrow'), 'blindness-deafness', 1), 'blur', 2)
assert.ok(wizardBookIssues(freeHigh, data).some((x) => x.includes('3/2, 1 in eccesso')), 'Only two free advancement spells may be level 2 at wizard level 3')
const legacyItalian = { ...create(3), playerDetails: { ...create(3).playerDetails, 'spell.1.0.name': 'Dardo Incantato', 'spell.1.0.prepared': 'true' } }
const translatedData = { ...data, spells: data.spells.map((x) => x.index === 'magic-missile' ? { ...x, nameIt: 'Magic Missile', aliases: ['Dardo Incantato', 'Magic Missile'] } : x) }
assert.doesNotThrow(() => castWizardSpell(legacyItalian, translatedData, casting('spell.1.0', 1)), 'Language switches must preserve old name-only spell references')
const originalSerialized = JSON.stringify(first)
assert.throws(() => castWizardSpell(first, data, casting(root, 3, { overchannel: true, dice: '8d6', selfDamage: '100000' })))
assert.equal(JSON.stringify(first), originalSerialized, 'Failed casts must not consume slots or modify HP')

const { withWizardCatalog, subclassOptions, subclassMinimumLevel, applyCreation } = await import('../src/utils/PlayerCreation.ts')
const { improveWizard, replaceWizardCantrip, copyWizardBook, restoreWizardBackup } = await import('../src/utils/Wizard.ts')
const wizardCatalog = json('wizard-catalog')
const expanded = withWizardCatalog(data, wizardCatalog)
assert.equal(subclassOptions(create(1), expanded).length, 26, 'All page entries should be visible before unlock')
assert.equal(subclassOptions(create(3, '2024'), expanded).length, 1, 'Do not pass 2014-only subclasses off as 2024')
assert.equal(expanded.subclasses.filter((x) => x.index === 'evocation').length, 1)
for (const option of subclassOptions(create(2), expanded)) {
    const selected = { ...create(2), playerDetails: { ...create(2).playerDetails, 'creation.subclass': option.index } }
    assert.equal(subclassMinimumLevel(selected, option, expanded), 2)
    assert.equal(selectedOrigins(selected, expanded).subclass.index, option.index)
    assert.doesNotThrow(() => applyCreation(selected, expanded))
    if (option.index !== 'evocation') assert.ok(!applyCreation(selected, expanded).playerDetails.classFeatures.includes('Evocation Savant'))
}
for (const row of wizardCatalog.levels) {
    const original = data.levels.find((x) => x.index === `wizard-${row.level}`).spellcasting
    assert.equal(row.cantrips, original.cantrips_known)
    for (let i = 1; i <= 9; i++) assert.equal(row.slots[i - 1], original[`spell_slots_level_${i}`] || 0)
}
let advanced = applyCreation(improveWizard(create(4), 4, 'intelligence', 'intelligence'), data)
assert.equal(advanced.intelligence, '18')
assert.equal(advanced.playerDetails.spellDC, '14')
assert.throws(() => improveWizard(advanced, 4, 'intelligence', 'intelligence'), /già/)
assert.throws(() => improveWizard(create(3), 4, 'intelligence', 'intelligence'))
assert.throws(() => improveWizard({ ...create(4), intelligence: '19' }, 4, 'intelligence', 'intelligence'), /20/)
assert.equal(improveWizard(create(4), 4, '', '', 'Alert').playerDetails.feats, 'Alert')
assert.equal(improveWizard(create(4), 4, '', '', '', true).intelligence, '16')
assert.throws(() => improveWizard(create(19, '2024'), 19, 'intelligence', 'intelligence'))
let formulas = add(create(3), 'light')
formulas.playerDetails['wizard.cantripFormulas'] = 'true'
assert.throws(() => replaceWizardCantrip(formulas, data, 'spell.0.0', 'mage-hand'), /riposo lungo/)
formulas = wizardRest(formulas, true)
const swapped = replaceWizardCantrip(formulas, data, 'spell.0.0', 'mage-hand')
assert.equal(swapped.playerDetails['spell.0.0.index'], 'mage-hand')
assert.throws(() => replaceWizardCantrip(swapped, data, 'spell.0.0', 'light'), /solo/)
assert.ok(applyCreation(formulas, data).playerDetails.classFeatures.includes('Cantrip Formulas'))
assert.throws(() => replaceWizardCantrip({ ...formulas, level: '2' }, data, 'spell.0.0', 'mage-hand'))
let bookSheet = add(add(create(3), 'magic-missile'), 'shield', 1, false)
bookSheet.playerDetails['coins.MO'] = '100'
const backup = copyWizardBook(bookSheet, data, false)
assert.equal(backup.playerDetails['coins.MO'], '80')
const rebuilt = copyWizardBook(backup, data, true)
assert.equal(rebuilt.playerDetails['coins.MO'], '70')
assert.equal(rebuilt.playerDetails['spell.1.1.lost'], 'true')
assert.equal(spellRowState(rebuilt, 1, 1).available, false)
assert.throws(() => castWizardSpell(rebuilt, data, casting('spell.1.1', 1)), /perduto/)
assert.equal(rebuilt.playerDetails['wizard.bookBackup'], backup.playerDetails['wizard.bookBackup'])
const recoveredBackup = restoreWizardBackup(rebuilt, data)
assert.equal(recoveredBackup.playerDetails['coins.MO'], '70', 'Retrieving a physical backup should not charge for a new copy')
assert.equal(recoveredBackup.playerDetails['spell.1.1.lost'], 'false')
const recopied = copyWizardSpell(rebuilt, data, 'shield')
assert.equal(recopied.playerDetails['spell.1.1.lost'], 'false')
assert.equal(recopied.playerDetails['coins.MO'], '20')
assert.throws(() => restoreWizardBackup({ ...rebuilt, playerDetails: { ...rebuilt.playerDetails, 'wizard.bookBackup': 'null' } }, data))
assert.equal(backup.playerDetails['coins.MO'], '80', 'Restoring must not mutate stored backups')
console.log('Full wizard page checks passed: 26 subclasses, sources, edition gates, progression, advancements, optional cantrip swaps and spellbook loss/recovery.')

const { selectedWizardFeatures, savedWizardFeatures, featureResourceRemaining, featureResourceKey, spendWizardFeature, wizardFeatureGrants, wizardBook } = await import('../src/utils/Wizard.ts')
const { initiativeBonus } = await import('../src/utils/CharacterSheets.ts')
const subclassMage = (id, level = 14, details = {}) => enableCreation({ ...newCharacterSheet(), name: 'Specialista', kind: 'PG', level: String(level), intelligence: '16', dexterity: '12', playerDetails: { 'creation.class': 'wizard', 'creation.subclass': id, ...details } }, expanded)
for (const option of expanded.subclasses.filter((x) => x.features)) {
    for (const level of [1,2,6,10,14]) {
        const character = subclassMage(option.index, level)
        const selected = selectedWizardFeatures(character, expanded)
        for (const feature of option.features) {
            const unlocked = level >= feature.level && !feature.choice
            assert.equal(selected.some((x) => x.index === feature.index), unlocked, `${option.name}: ${feature.name} at ${level}`)
            assert.equal(character.playerDetails.classFeatures.includes(feature.name + ' (livello '), unlocked)
            if (!unlocked) continue
            const classified = pdfAbilities(character).find((x) => x.name === feature.name)
            assert.equal(classified?.activation, feature.activation)
            if (feature.rounds) assert.equal(classified.template.remainingTurns, feature.rounds)
        }
        assert.equal(savedWizardFeatures(character).length, selected.length)
        assert.doesNotThrow(() => wizardRest(character, true))
        assert.equal(Object.values(applyCreation(character, expanded).playerDetails).filter((x) => x === 'Animate Dead').length, Object.values(character.playerDetails).filter((x) => x === 'Animate Dead').length, 'Applying creation must not duplicate granted spells')
    }
}
let bladesinger = subclassMage('wizard-bladesinging', 2, { 'wizard.weapon': 'rapier' })
assert.equal(bladesinger.playerDetails['proficiency.Leggere'], 'true')
assert.equal(bladesinger.playerDetails['skill.Intrattenere.proficient'], 'true')
const song = selectedWizardFeatures(bladesinger, expanded).find((x) => x.name === 'Bladesong')
assert.equal(featureResourceRemaining(bladesinger, song), 2)
bladesinger = spendWizardFeature(spendWizardFeature(bladesinger, song), song)
assert.throws(() => spendWizardFeature(bladesinger, song), /rimangono/)
assert.equal(featureResourceRemaining(wizardRest(bladesinger, false), song), 0)
assert.equal(featureResourceRemaining(wizardRest(bladesinger, true), song), 2)
assert.equal(initiativeBonus(subclassMage('wizard-war-magic', 2)), '+4')
assert.equal(initiativeBonus(subclassMage('wizard-chronurgy', 2)), '+4')
assert.equal(initiativeBonus(subclassMage('wizard-lore-mastery-ua', 2, { 'wizard.initiativeAbility': 'intelligence' })), '+3')
let necromancer = subclassMage('wizard-necromancy', 6)
assert.equal(wizardBook(necromancer, expanded).filter((x) => x.spell?.index === 'animate-dead').length, 1)
assert.equal(wizardBookIssues(necromancer, expanded).some((x) => x.includes('animate-dead')), false)
assert.equal(wizardBook(applyCreation({ ...necromancer, level: '5' }, expanded), expanded).length, 0, 'Locked auto-grants must be removed')
let transmuter = subclassMage('wizard-transmutation', 10)
const polymorph = wizardBook(transmuter, expanded).find((x) => x.spell?.index === 'polymorph')
assert.ok(polymorph)
assert.throws(() => castWizardSpell(transmuter, expanded, casting(polymorph.root,4,{ mode:'feature' })), /condizioni/)
transmuter = castWizardSpell(transmuter, expanded, casting(polymorph.root,4,{ mode:'feature', confirmFeatureConditions:true }))
assert.equal(transmuter.playerDetails['slots.4.used'] || '0', '0')
assert.throws(() => castWizardSpell(transmuter, expanded, casting(polymorph.root,4,{ mode:'feature', confirmFeatureConditions:true })), /rimangono/)
assert.doesNotThrow(() => castWizardSpell(wizardRest(transmuter,false), expanded, casting(polymorph.root,4,{ mode:'feature', confirmFeatureConditions:true })))
let illusionist = subclassMage('wizard-illusion', 2)
assert.equal(spellSelection(illusionist,expanded).cantrips,0, 'Granted cantrips must not consume class selections')
illusionist = applyCreation({ ...add(subclassMage('wizard-illusion',1),'minor-illusion'),level:'2',playerDetails:{ ...add(subclassMage('wizard-illusion',1),'minor-illusion').playerDetails,'wizard.grantChoice.wizard-illusion-improved-minor-illusion':'light' } }, expanded)
assert.ok(wizardBook(illusionist,expanded).some((x) => x.spell?.index === 'light'))
assert.equal(spellSelection(illusionist,expanded).cantrips,1)
const prismariFeatures = expanded.features.filter((x) => x.subclass?.index === 'wizard-mage-of-prismari-ua' && x.choice)
const prismari = subclassMage('wizard-mage-of-prismari-ua', 14, { 'wizard.subclass.choice.6':prismariFeatures[0].index,'wizard.subclass.choice.10':prismariFeatures[1].index,'wizard.subclass.choice.14':prismariFeatures[2].index,'wizard.skill.0':'acrobatics','wizard.skill.1':'nature' })
assert.equal(selectedWizardFeatures(prismari,expanded).filter((x) => x.choice).length,3)
assert.equal(prismari.playerDetails['save.dexterity.proficient'],'true')
const duplicate = applyCreation({ ...prismari, playerDetails:{ ...prismari.playerDetails,'wizard.subclass.choice.10':prismariFeatures[0].index } }, expanded)
assert.equal(selectedWizardFeatures(duplicate,expanded).filter((x) => x.choice).length,2)
let onomancer = subclassMage('wizard-onomancy-ua',2)
const bane = wizardBook(onomancer,expanded).find((x) => x.spell?.index === 'bane')
assert.equal(bane.state.alwaysPrepared,true)
onomancer = castWizardSpell(onomancer,expanded,casting(bane.root,1,{ mode:'feature',confirmFeatureConditions:true }))
const naming = selectedWizardFeatures(onomancer,expanded).find((x) => x.name === 'Fateful Naming')
assert.equal(featureResourceRemaining(onomancer,naming),2)
let abjurer = add(subclassMage('wizard-abjuration',2),'shield')
abjurer = castWizardSpell(abjurer,expanded,casting('spell.1.0',1,{ createWard:true }))
assert.equal(abjurer.playerDetails['wizard.ward.current'],'7')
abjurer.playerDetails['wizard.ward.current']='1'
abjurer = castWizardSpell(abjurer,expanded,casting('spell.1.0',1))
assert.equal(abjurer.playerDetails['wizard.ward.current'],'3')
assert.throws(() => castWizardSpell(abjurer,expanded,casting('spell.1.0',1,{ createWard:true })))
let diviner = add(subclassMage('wizard-divination',6),'detect-thoughts')
diviner.playerDetails['slots.1.used']='1'
diviner = castWizardSpell(diviner,expanded,casting('spell.2.0',2,{ recoverSlot:1 }))
assert.equal(diviner.playerDetails['slots.1.used'],'0')
assert.equal(diviner.playerDetails['slots.2.used'],'1')
const scribe = subclassMage('wizard-order-of-scribes',2,{ 'wizard.quill':'true' })
assert.equal(copyCost(scribe,spell('shield')).gold,50)
assert.equal(copyCost(scribe,spell('shield')).hours,1/30)
assert.equal(copyCost(subclassMage('wizard-order-of-scribes-ua',2,{ 'wizard.quill':'true' }),spell('shield')).gold,25)
let scribeRitual = add(scribe,'detect-magic',0,false)
scribeRitual = castWizardSpell(scribeRitual,expanded,casting('spell.1.0',1,{ mode:'ritual',fastRitual:true }))
assert.throws(() => castWizardSpell(scribeRitual,expanded,casting('spell.1.0',1,{ mode:'ritual',fastRitual:true })))
assert.doesNotThrow(() => castWizardSpell(wizardRest(scribeRitual,true),expanded,casting('spell.1.0',1,{ mode:'ritual',fastRitual:true })))
const theurge = subclassMage('wizard-theurgy-ua',6)
const channels = selectedWizardFeatures(theurge,expanded).filter((x) => x.resource)
assert.equal(featureResourceKey(channels[0]),featureResourceKey(channels[1]))
assert.equal(featureResourceRemaining(spendWizardFeature(theurge,channels[0]),channels[1]),1)
assert.equal(wizardFeatureGrants(subclassMage('wizard-mage-of-lorehold-ua',2),expanded).length,2)
assert.equal(wizardFeatureGrants(subclassMage('wizard-mage-of-lorehold-ua',9),expanded).length,10)
assert.deepEqual(savedWizardFeatures({ ...theurge, playerDetails:{ ...theurge.playerDetails,'wizard.featureRules':'[{"index":"bad","name":"Bad","activation":"active","level":2,"subclass":{"index":"wizard-theurgy-ua"},"desc":[],"resource":{"max":null,"reset":"long"}}]' } }),[])
console.log('Subclass checks passed: 129 features, unlock levels, activation, timers, grants, choices, resources, rests, initiative, ward and free casts.')
const { spendWizardPortent } = await import('../src/utils/Wizard.ts')
let portentMage = subclassMage('wizard-divination',14,{ 'wizard.portent.0':'20','wizard.portent.1':'3','wizard.portent.2':'12' })
const portent = selectedWizardFeatures(portentMage,expanded).find((x) => x.name === 'Portent')
assert.equal(featureResourceRemaining(portentMage,portent),3)
portentMage = spendWizardPortent(portentMage,2)
assert.equal(featureResourceRemaining(portentMage,portent),2)
assert.throws(() => spendWizardPortent(portentMage,2))
assert.throws(() => spendWizardPortent(subclassMage('wizard-divination',13),2))
assert.equal(wizardRest(portentMage,true).playerDetails['wizard.portent.2'],undefined)
let runecrafter = subclassMage('wizard-runecrafter-ua',10,{ 'slots.1.used':'1' })
const rune = selectedWizardFeatures(runecrafter,expanded).find((x) => x.name === 'Runic Empowerment')
runecrafter.playerDetails[featureResourceKey(rune)] = '0'
assert.equal(featureResourceRemaining(recoverWizardSlots(runecrafter,{1:'1'}),rune),2)
const conjurer = add(subclassMage('wizard-conjuration',6),'misty-step')
const transport = selectedWizardFeatures(conjurer,expanded).find((x) => x.name === 'Benign Transportation')
conjurer.playerDetails[featureResourceKey(transport)] = '0'
assert.equal(featureResourceRemaining(castWizardSpell(conjurer,expanded,casting('spell.2.0',2)),transport),1)
const knownPolymorph = applyCreation(add(subclassMage('wizard-transmutation',9),'polymorph'),expanded)
const grantedPolymorph = applyCreation({ ...knownPolymorph,level:'10' },expanded)
assert.equal(grantedPolymorph.playerDetails['spell.4.0.grantGenerated'],'false')
assert.equal(applyCreation({ ...grantedPolymorph,level:'9' },expanded).playerDetails['spell.4.0.index'],'polymorph','Losing a grant must preserve manually learned spells')
const changedClass = applyCreation({ ...necromancer,playerDetails:{ ...necromancer.playerDetails,'creation.class':'fighter','creation.subclass':'' } },expanded)
assert.ok(!Object.values(changedClass.playerDetails).includes('animate-dead'),'Changing class removes automatically granted wizard spells')
