import { useState } from 'react'
import type { CharacterSheet } from '../utils/CharacterSheets'
import { labelOf, type CreationData } from '../utils/PlayerCreation'
import { castWizardSpell, copyCost, copyWizardSpell, copyWizardBook, restoreWizardBackup, improveWizard, replaceWizardCantrip, recoverWizardSlots, wizardBook, wizardRest, wizardRules, wizardFeatureGrants, type WizardCast } from '../utils/Wizard'
import { characterFields } from '../utils/CharacterSheets'

export function WizardSpellcasting({ sheet, data, onChange }: { sheet: CharacterSheet; data: CreationData; onChange: (sheet: CharacterSheet) => void }) {
    const [error, setError] = useState('')
    const [copy, setCopy] = useState('')
    const [recovery, setRecovery] = useState<Record<number, string>>({})
    const [cast, setCast] = useState<WizardCast>({ root: '', slot: 1, mode: 'slot', overchannel: false, selfDamage: '', empowered: false, dice: '', damage: '', outcome: 'hit', targets: [] })
    const [rest, setRest] = useState<'short' | 'long'>()
    const [bookOperation, setBookOperation] = useState<'backup' | 'restore' | 'recover'>()
    const [oldCantrip, setOldCantrip] = useState('')
    const [newCantrip, setNewCantrip] = useState('')
    const rules = wizardRules(sheet), d = sheet.playerDetails ?? {}, book = wizardBook(sheet, data)
    if (!rules.wizard) return null
    const selected = book.find((x) => x.root === cast.root)
    const featureGrant = selected?.spell && wizardFeatureGrants(sheet, data).find((x) => x.index === selected.spell?.index && x.free)
    const scribes = rules.edition === '2014' && rules.level >= 2 && ['wizard-order-of-scribes','wizard-order-of-scribes-ua'].includes(d['creation.subclass'])
    const divination = rules.edition === '2014' && rules.level >= 6 && d['creation.subclass'] === 'wizard-divination'
    const abjuration = rules.edition === '2014' && rules.level >= 2 && d['creation.subclass'] === 'wizard-abjuration'
    const copySpell = data.spells.find((x) => x.index === copy)
    const copyable = data.spells.filter((x) => x.level > 0 && x.classes.some((c) => c.index === 'wizard') && Number(d[`slots.${x.level}.total`]) > 0 && !book.some((row) => row.spell?.index === x.index && !row.state.lost))
    const missing = Math.max(0, rules.bookMinimum - book.filter((x) => x.level > 0 && d[`${x.root}.learned`] !== 'copied' && d[`${x.root}.learned`] !== 'savant' && d[`${x.root}.learned`] !== 'feature').length)
    function run(action: () => CharacterSheet) {
        try { onChange(action()); setError('') } catch (e) { setError(e instanceof Error ? e.message : 'Operazione non riuscita.') }
    }
    function detail(key: string, value: string) { onChange({ ...sheet, playerDetails: { ...d, [key]: value } }); setError('') }
    function choice(key: string, level: number, actionOnly = false) {
        const options = book.filter((x) => x.level === level && x.spell && (!actionOnly || x.spell.casting_time === '1 action'))
        return <label className="player-field" key={key}><span>{key.includes('mastery') ? `Spell Mastery · livello ${level}` : `Incantesimo caratteristico ${key.endsWith('0') ? 1 : 2}`}</span>
            <select value={options.some((x) => x.root === d[key]) ? d[key] : ''} onChange={(e) => detail(key, e.target.value)}><option value="">Scegli dal libro…</option>{options.map((x) => <option key={x.root} value={x.root} disabled={key.includes('signature') && [d['wizard.signature.0'], d['wizard.signature.1']].includes(x.root) && d[key] !== x.root}>{x.name}</option>)}</select></label>
    }
    return <section className="player-box wizard-rules">
        <h3>Libro e privilegi del mago · {rules.edition}</h3>
        <label className="player-field"><span>Aspetto del libro degli incantesimi</span><input value={d['wizard.bookAppearance'] ?? ''} onChange={(e) => detail('wizard.bookAppearance', e.target.value)} placeholder="Materiali, copertina e particolarità del libro" /></label>
        <p className="player-hint">Libro: {book.filter((x) => x.level > 0).length} incantesimi. Scelte iniziali e di livello: {rules.bookMinimum}; {missing ? `${missing} ancora da annotare` : 'annotate'}. Due nuove scelte a ogni livello; le copie aggiuntive non hanno un limite di quantità.</p>
        {rules.savantChoices > 0 && <p className="player-hint">Evocation Savant 2024: {rules.savantChoices} scelte gratuite di evocazione totali. Le prime due, dal livello 3, devono essere di livello 1–2; poi una per ogni nuovo livello di slot. Indicale nelle righe del libro.</p>}
        <div className="player-two-fields">
            <section className="player-box"><h3>Copia nel libro</h3>
                {scribes && <label className="player-check"><input type="checkbox" checked={d['wizard.quill'] === 'true'} onChange={(e) => detail('wizard.quill', String(e.target.checked))} /><span>Uso Wizardly Quill per la copia</span></label>}
                <label className="player-field"><span>Incantesimo da copiare</span><select value={copyable.some((x) => x.index === copy) ? copy : ''} onChange={(e) => setCopy(e.target.value)}><option value="">Seleziona…</option>{copyable.map((x) => <option key={x.index} value={x.index}>{labelOf(x)} · livello {x.level}</option>)}</select></label>
                {copySpell && <p className="player-hint">{copyCost(sheet, copySpell).gold} MO · {copyCost(sheet, copySpell).hours < 1 ? `${Math.round(copyCost(sheet, copySpell).hours * 60)} minuti` : `${copyCost(sheet, copySpell).hours} ore`}{rules.savantDiscount && copySpell.school?.index === rules.savantSchool ? ' · costo e tempo dimezzati' : ''}. Disponibili: {d['coins.MO'] || 0} MO.</p>}
                <button type="button" disabled={!copyable.some((x) => x.index === copy)} onClick={() => run(() => copyWizardSpell(sheet, data, copy))}>Conferma copia e spesa delle MO</button>
            </section>
            <section className="player-box"><h3>Recupero Arcano</h3>
                <p className="player-hint">Dopo un riposo breve: massimo {rules.recoveryBudget} livelli di slot; nessuno slot di livello 6 o superiore. {d['wizard.recovery.used'] === 'true' ? 'Già utilizzato.' : rules.edition === '2014' ? 'Una volta al giorno.' : 'Una volta per riposo lungo.'}</p>
                <div className="player-three-fields">{[1, 2, 3, 4, 5].filter((level) => Number(d[`slots.${level}.total`]) > 0).map((level) => <label className="player-field" key={level}><span>Livello {level} · spesi {d[`slots.${level}.used`] || 0}</span><input type="number" min="0" max={Number(d[`slots.${level}.used`]) || 0} step="1" value={recovery[level] ?? ''} onChange={(e) => setRecovery({ ...recovery, [level]: e.target.value })} /></label>)}</div>
                <button type="button" disabled={d['wizard.recovery.used'] === 'true'} onClick={() => run(() => recoverWizardSlots(sheet, recovery))}>Conferma recupero dopo riposo breve</button>
            </section>
        </div>
        <section className="player-box"><h3>Copia di sicurezza e libro perduto</h3><p className="player-hint">Trascrivere dal proprio libro costa 10 MO e un’ora per livello di ogni magia. Se il libro è perduto, puoi ricostruire solo gli incantesimi preparati; gli altri rimangono annotati come perduti finché non li ritrovi.</p><div className="wizard-rest"><button type="button" onClick={() => setBookOperation('backup')}>Copia di sicurezza</button><button type="button" onClick={() => setBookOperation('restore')}>Ricostruisci dai preparati</button>{d['wizard.bookBackup'] && <button type="button" onClick={() => setBookOperation('recover')}>Recupera copia di sicurezza</button>}</div>{bookOperation && <div><p>{bookOperation === 'recover' ? 'Confermi di aver recuperato la copia di sicurezza? Le magie aggiunte dopo la copia restano da ritrovare.' : <>Confermi la trascrizione{bookOperation === 'restore' ? ' dai soli preparati, segnando le altre magie come perdute' : ' del libro completo'} e la spesa delle MO?</>}</p><button type="button" onClick={() => { run(() => bookOperation === 'recover' ? restoreWizardBackup(sheet, data) : copyWizardBook(sheet, data, bookOperation === 'restore')); setBookOperation(undefined) }}>Conferma trascrizione</button> <button type="button" onClick={() => setBookOperation(undefined)}>Annulla</button></div>}{d['wizard.bookCopy.note'] && <p className="player-hint">{d['wizard.bookCopy.note']}</p>}</section>
        {(rules.edition === '2024' || rules.level >= 3) && <section className="player-box"><h3>{rules.edition === '2014' ? 'Cantrip Formulas · regola opzionale' : 'Sostituzione di un trucchetto'}</h3>{rules.edition === '2014' && <label className="player-check"><input type="checkbox" checked={d['wizard.cantripFormulas'] === 'true'} onChange={(e) => detail('wizard.cantripFormulas', String(e.target.checked))} /><span>Abilita Cantrip Formulas con il DM</span></label>}<p className="player-hint">Dopo un riposo lungo, consultando il libro, puoi sostituire un solo trucchetto da mago. {d['wizard.cantripReplacement.used'] === 'true' && 'Sostituzione già effettuata.'}</p><div className="player-two-fields"><label className="player-field"><span>Trucchetto da sostituire</span><select value={oldCantrip} onChange={(e) => setOldCantrip(e.target.value)}><option value="">Seleziona…</option>{book.filter((x) => x.level === 0).map((x) => <option key={x.root} value={x.root}>{x.name}</option>)}</select></label><label className="player-field"><span>Nuovo trucchetto</span><select value={newCantrip} onChange={(e) => setNewCantrip(e.target.value)}><option value="">Seleziona…</option>{data.spells.filter((x) => x.level === 0 && x.classes.some((c) => c.index === 'wizard') && !book.some((row) => row.level === 0 && row.spell?.index === x.index)).map((x) => <option key={x.index} value={x.index}>{labelOf(x)}</option>)}</select></label></div><button type="button" disabled={!oldCantrip || !newCantrip || d['wizard.longRest.completed'] !== 'true' || d['wizard.cantripReplacement.used'] === 'true' || rules.edition === '2014' && d['wizard.cantripFormulas'] !== 'true'} onClick={() => run(() => replaceWizardCantrip(sheet, data, oldCantrip, newCantrip))}>Conferma sostituzione dopo riposo lungo</button></section>}
        {(rules.mastery || rules.signature) && <div className="player-two-fields">
            {rules.mastery && <section className="player-box"><h3>Spell Mastery</h3>{[1, 2].map((level) => choice(`wizard.mastery.${level}`, level, rules.edition === '2024'))}<p className="player-hint">Lancio gratuito solo al livello base. {rules.edition === '2014' ? 'Devono essere preparati; cambi le scelte dopo 8 ore di studio.' : 'Sempre preparati, fuori dal limite; solo magie con tempo di lancio di un’azione. Puoi cambiarne una dopo un riposo lungo.'}</p></section>}
            {rules.signature && <section className="player-box"><h3>Signature Spells</h3>{[0, 1].map((i) => choice(`wizard.signature.${i}`, 3))}<p className="player-hint">Sempre preparati, fuori dal limite. Un lancio gratuito ciascuno al livello 3 per riposo breve o lungo.</p></section>}
        </div>}
        <section className="player-box"><h3>Lancio ed effetti</h3>
            <div className="player-three-fields">
                <label className="player-field"><span>Incantesimo del libro</span><select value={selected ? cast.root : ''} onChange={(e) => { const row = book.find((x) => x.root === e.target.value); setCast({ ...cast, root: e.target.value, slot: row?.level ?? 1, mode: 'slot', empowered: false, overchannel: false, targets: [], damage: '', dice: '', selfDamage: '', outcome: 'hit', confirmFeatureConditions: false, fastRitual: false, recoverSlot: 0, createWard: false }) }}><option value="">Seleziona…</option>{book.map((x) => <option key={x.root} value={x.root}>{x.name}{x.level ? x.state.available ? ' · preparato' : ' · nel libro' : ' · trucchetto'}</option>)}</select></label>
                <label className="player-field"><span>Livello del lancio</span><select value={cast.slot} onChange={(e) => setCast({ ...cast, slot: Number(e.target.value) })}>{(selected?.level === 0 ? [0] : [1,2,3,4,5,6,7,8,9].filter((l) => l >= (selected?.level ?? 1) && Number(d[`slots.${l}.total`]) > 0)).map((l) => <option key={l} value={l}>{l} · disponibili {Math.max(0, Number(d[`slots.${l}.total`] || 0) - Number(d[`slots.${l}.used`] || 0))}</option>)}</select></label>
                <label className="player-field"><span>Modalità</span><select value={cast.mode} onChange={(e) => setCast({ ...cast, mode: e.target.value as WizardCast['mode'] })}><option value="slot">{selected?.level === 0 ? 'Trucchetto · senza slot' : 'Consuma slot'}</option>{selected?.spell?.ritual && <option value="ritual">Rituale · senza preparazione</option>}{featureGrant && <option value="feature">{featureGrant.feature.name} · senza slot</option>}{rules.mastery && <option value="mastery">Spell Mastery · senza slot</option>}{rules.signature && <option value="signature">Signature Spell · senza slot</option>}</select></label>
            </div>
            {selected?.spell?.ritual && <p className="player-hint">Rituale disponibile dal libro anche senza preparazione: richiede 10 minuti aggiuntivi.</p>}
            {featureGrant && cast.mode === 'feature' && <><p className="player-hint">{featureGrant.feature.desc.join(' ')}</p><label className="player-check"><input type="checkbox" checked={!!cast.confirmFeatureConditions} onChange={(e) => setCast({ ...cast, confirmFeatureConditions: e.target.checked })} /><span>Confermo le condizioni del privilegio per questo lancio gratuito</span></label></>}
            {scribes && cast.mode === 'ritual' && <label className="player-check"><input type="checkbox" checked={!!cast.fastRitual} disabled={d['wizard.fastRitual.used'] === 'true'} onChange={(e) => setCast({ ...cast, fastRitual: e.target.checked })} /><span>Awakened Spellbook · rituale senza 10 minuti aggiuntivi (una volta per riposo lungo)</span></label>}
            {divination && cast.mode === 'slot' && selected?.spell?.school?.index === 'divination' && cast.slot >= 2 && <label className="player-field"><span>Expert Divination · slot da recuperare</span><select value={cast.recoverSlot || 0} onChange={(e) => setCast({ ...cast, recoverSlot: Number(e.target.value) })}><option value="0">Nessuno</option>{[1,2,3,4,5].filter((l) => l < cast.slot && Number(d[`slots.${l}.used`]) > 0).map((l) => <option key={l} value={l}>Livello {l}</option>)}</select></label>}
            {abjuration && selected?.spell?.school?.index === 'abjuration' && selected.level >= 1 && d['wizard.ward.created'] !== 'true' && <label className="player-check"><input type="checkbox" checked={!!cast.createWard} onChange={(e) => setCast({ ...cast, createWard: e.target.checked })} /><span>Crea Arcane Ward · una volta per riposo lungo</span></label>}
            {rules.potent && <p className="player-hint">Potent Cantrip: metà danno del trucchetto dopo TS riuscito{rules.edition === '2024' ? ' o attacco mancato' : ''}, senza effetti aggiuntivi.</p>}
            {rules.sculpt && selected?.spell?.school?.index === 'evocation' && <label className="player-field"><span>Sculpt Spells · creature visibili protette (massimo {1 + cast.slot}; separate da virgole)</span><input value={cast.targets.join(',')} onChange={(e) => setCast({ ...cast, targets: e.target.value.split(',') })} placeholder="Nome creatura, nome creatura" /></label>}
            <div className="player-three-fields">
                <label className="player-field"><span>Danno di un tiro, prima dei privilegi</span><input type="number" min="0" step="1" value={cast.damage} onChange={(e) => setCast({ ...cast, damage: e.target.value })} /></label>
                <label className="player-field"><span>Esito del bersaglio</span><select value={cast.outcome} onChange={(e) => setCast({ ...cast, outcome: e.target.value as WizardCast['outcome'] })}><option value="hit">Colpito / TS fallito</option><option value="save">TS riuscito</option><option value="miss">Attacco mancato</option></select></label>
                {rules.empowered && <label className="player-check"><input type="checkbox" checked={cast.empowered} onChange={(e) => setCast({ ...cast, empowered: e.target.checked })} /><span>Empowered Evocation · Intelligenza a un solo tiro</span></label>}
            </div>
            {rules.overchannel && <><label className="player-check"><input type="checkbox" checked={cast.overchannel} onChange={(e) => setCast({ ...cast, overchannel: e.target.checked })} /><span>Attiva Overchannel · usi da ultimo riposo lungo: {d['wizard.overchannel.used'] || 0}</span></label>{cast.overchannel && <div className="player-two-fields"><label className="player-field"><span>Dadi del tiro da massimizzare</span><input placeholder="8d6" value={cast.dice} onChange={(e) => setCast({ ...cast, dice: e.target.value })} /></label>{Number(d['wizard.overchannel.used']) > 0 && <label className="player-field"><span>Danno necrotico subito · tira {(Number(d['wizard.overchannel.used']) + 1) * cast.slot}d12</span><input type="number" min="0" step="1" value={cast.selfDamage} onChange={(e) => setCast({ ...cast, selfDamage: e.target.value })} /></label>}</div>}<p className="player-hint">Massimizza i dadi del danno; per effetti con più tiri applica il massimo anche agli altri tiri previsti dalla magia{rules.edition === '2024' ? ' nel turno del lancio' : ''}. I danni necrotici dei riutilizzi si applicano ai tuoi PF temporanei e attuali.</p></>}
            <button type="button" disabled={!selected?.spell} onClick={() => run(() => castWizardSpell(sheet, data, cast))}>Conferma lancio</button>
            {d['wizard.lastCast'] && <p className="player-hint" role="status">{d['wizard.lastCast']} I danni ai bersagli si applicano nelle card dei turni.</p>}
        </section>
        <div className="wizard-rest"><button type="button" onClick={() => setRest('short')}>Riposo breve</button><button type="button" onClick={() => setRest('long')}>Riposo lungo / nuova giornata</button></div>
        {rest && <div className="player-hint"><p>{rest === 'long' ? 'Confermi il riposo lungo e l’inizio della nuova giornata? Ripristina slot, Recupero Arcano, Overchannel, lanci gratuiti e usi dei privilegi della sottoclasse.' : 'Confermi il riposo breve? Ripristina i lanci gratuiti caratteristici e le risorse recuperabili con riposo breve; scegli separatamente gli slot per Recupero Arcano.'}</p><button type="button" onClick={() => { run(() => wizardRest(sheet, rest === 'long')); setRest(undefined) }}>Conferma riposo</button> <button type="button" onClick={() => setRest(undefined)}>Annulla</button></div>}
        {error && <p className="creation-warning" role="alert">{error}</p>}
    </section>
}

export function WizardAdvancement({ sheet, onChange }: { sheet: CharacterSheet; onChange: (sheet: CharacterSheet) => void }) {
    const [level, setLevel] = useState(4)
    const [first, setFirst] = useState('intelligence')
    const [second, setSecond] = useState('intelligence')
    const [mode, setMode] = useState('scores')
    const [feat, setFeat] = useState('')
    const [error, setError] = useState('')
    const r = wizardRules(sheet), d = sheet.playerDetails ?? {}
    if (!r.wizard) return null
    const levels = (r.edition === '2014' ? [4,8,12,16,19] : [4,8,12,16]).filter((x) => x <= r.level)
    const scores = ['strength','dexterity','constitution','intelligence','wisdom','charisma'] as const
    return <details className="player-box wizard-rules"><summary>Regole e avanzamento del mago · {r.edition}</summary>
        <p className="player-hint">Riferimenti della pagina Wizard (2014). Dadi vita: d6. PF iniziali: 6 + Costituzione; ai livelli successivi d6 oppure 4 + Costituzione. La creazione guidata usa 4; puoi annotare manualmente i PF ottenuti dai dadi. Per entrare o uscire dalla classe in multiclasse occorre Intelligenza almeno 13. Il livello della scheda indica il livello da mago: la progressione multiclasse non viene calcolata qui.</p>
        <p className="player-hint">Tiri salvezza: Intelligenza e Saggezza. Due competenze a scelta tra Arcano, Storia, Intuizione, Indagare, Medicina e Religione. Nessuna competenza iniziale in armature o strumenti; armi: pugnali, dardi, fionde, bastoni e balestre leggere. Le scelte iniziali sono nella Creazione guidata.</p>
        <p className="player-hint">Equipaggiamento iniziale: bastone o pugnale, borsa dei componenti o focus arcano, dotazione da studioso o esploratore, libro degli incantesimi. Il focus può sostituire i materiali ammessi dalle regole; i componenti con costo e quelli consumati restano necessari.</p>
        <p className="player-hint">CD magie: 8 + competenza + Intelligenza. Attacco magico: competenza + Intelligenza. Nel 2014 puoi cambiare i preparati dopo un riposo lungo: lo studio richiede un minuto per livello di ciascuna magia preparata. Lanciare una magia non rimuove la sua preparazione.</p>
        {levels.length > 0 && <><h3>Aumento di caratteristiche / talento</h3><p className="player-hint">Due incrementi da +1, anche sulla stessa caratteristica; massimo 20. Per una scheda già compilata registra gli aumenti già inclusi, così non vengono applicati due volte.</p><div className="player-two-fields"><label className="player-field"><span>Avanzamento del livello</span><select value={level} onChange={(e) => setLevel(Number(e.target.value))}>{levels.map((x) => <option key={x} value={x}>{x}{d[`wizard.improvement.${x}`] ? ' · registrato' : ''}</option>)}</select></label><label className="player-field"><span>Scelta</span><select value={mode} onChange={(e) => setMode(e.target.value)}><option value="scores">Aumento delle caratteristiche</option><option value="feat">Talento scelto con il DM</option><option value="recorded">Già incluso nella scheda</option></select></label></div>
        {mode === 'scores' && <div className="player-two-fields">{[first,second].map((value,i) => <label className="player-field" key={i}><span>Incremento {i + 1} · +1</span><select value={value} onChange={(e) => (i ? setSecond : setFirst)(e.target.value)}>{scores.map((key) => <option key={key} value={key}>{characterFields[key]}</option>)}</select></label>)}</div>}{mode === 'feat' && <label className="player-field"><span>Nome del talento (verifica requisiti con il DM)</span><input value={feat} onChange={(e) => setFeat(e.target.value)} /></label>}
        <button type="button" disabled={!levels.includes(level) || !!d[`wizard.improvement.${level}`] || mode === 'feat' && !feat.trim()} onClick={() => { try { onChange(improveWizard(sheet, level, first, second, mode === 'feat' ? feat : '', mode === 'recorded')); setError('') } catch (e) { setError(e instanceof Error ? e.message : 'Avanzamento non riuscito.') } }}>Conferma avanzamento</button>
        <ul>{levels.filter((x) => d[`wizard.improvement.${x}`]).map((x) => <li key={x}>Livello {x}: {d[`wizard.improvement.${x}`]}</li>)}</ul></>}
        {error && <p role="alert" className="creation-warning">{error}</p>}
    </details>
}
